theme: jekyll-theme-tactile

# Name of website
title: A dockerized RESTful API for storing encrypted files

# Short description of your site
description: Dockerized RESTful API for storing encrypted files
